version: '3'

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    network_mode: 'host'

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - sko_data:/var/lib/mysql
    network_mode: 'host'

volumes:
  redis_data:
  sko_data:
